apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall-monitoring.name" . }}-tokens
  labels:
    {{- include "heimdall-monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  install-token: {{ .Values.global.installToken | quote }}
  alertmanager-token: {{ .Values.alerting.alertmanager.webhook.token | quote }}
  grafana-token: {{ .Values.alerting.grafana.webhook.token | quote }}
