{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heimdall-monitoring.name" . }}-gateway
  labels:
    {{- include "heimdall-monitoring.labels" . | nindent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "heimdall-monitoring.name" . }}-gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
{{- end }}
